import { Redis } from "@upstash/redis";
import type { HookContext } from "eve/hooks";
import winston from "winston";

/** How long an anonymous session's stored data outlives its last turn. */
export const anonymousRetentionSeconds = 24 * 60 * 60;

let client: Redis | undefined;

function redis(): Redis {
  client ??= Redis.fromEnv();
  return client;
}

/** SCAN's MATCH is a glob; a session id must only ever match itself. */
function escapeGlob(value: string): string {
  return value.replace(/[\\*?[\]]/g, "\\$&");
}

/**
 * Puts a 24-hour expiry on what an anonymous session has stored in AgentKit,
 * so a public demo does not keep visitors' data indefinitely. Run at the end
 * of every turn, which makes the 24 hours count from the session's last
 * turn.
 *
 * AgentKit 0.13 cannot do this itself: its memory has no expiry option, and
 * its chat-history `ttlSeconds` is one value for the whole deployment, which
 * would expire signed-in callers' history too.
 *
 * Only anonymous callers are touched, by the same caller rule as
 * agent/lib/agentkit-user.ts, and only the keys that module's session-keyed
 * user id produces. The key layout is the extension's, not adam's:
 * `agentkit:chat:<user>:<session>` and `agentkit:memory:<user>:<memory id>`,
 * with `:` in either id replaced by `_`. agent/extensions/agentkit.test.ts
 * fails if the extension stops writing where this expires.
 *
 * Memory ids are generated by the extension, so the session's memory keys
 * are found with SCAN under the session's own prefix. SCAN walks the whole
 * keyspace, so its cost grows with the database, not with the session.
 */
export async function expireAnonymousSession(
  ctx: Pick<HookContext, "session">,
): Promise<void> {
  const { id, auth } = ctx.session;
  if ((auth.current ?? auth.initiator)?.principalType !== "anonymous") return;

  const user = id.replaceAll(":", "_");
  const keys = [`agentkit:chat:${user}:${user}`];
  const match = `agentkit:memory:${escapeGlob(user)}:*`;
  let cursor = "0";
  do {
    const [next, page] = await redis().scan(cursor, { match, count: 1_000 });
    keys.push(...page);
    cursor = next;
  } while (cursor !== "0");

  const pipeline = redis().pipeline();
  for (const key of keys) pipeline.expire(key, anonymousRetentionSeconds);
  await pipeline.exec();
}

/**
 * The hook handler for every way a turn ends. A failed expiry is logged and
 * goes no further: it must not fail the turn it follows, and the session's
 * next turn sets the expiry again.
 */
export async function onAnonymousTurnEnded(
  _event: unknown,
  ctx: Pick<HookContext, "session">,
): Promise<void> {
  try {
    await expireAnonymousSession(ctx);
  } catch (error) {
    winston.warn("anonymous session expiry failed", {
      event: "anonymous_expiry_failed",
      sessionId: ctx.session.id,
      reason: String(error),
    });
  }
}
